-- 1. Create the Database
CREATE DATABASE IF NOT EXISTS CADP_SERV_AMER_REPORTING;

-- 2. Select the Database to use it
USE DATABASE CADP_SERV_AMER_REPORTING;

-- 3. Create the Schema inside that Database
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS STAGING;

-- 4. Verify the creation
SHOW SCHEMAS IN DATABASE CADP_SERV_AMER_REPORTING;

-- 5. Create a Virtual Warehouse
CREATE WAREHOUSE IF NOT EXISTS GENERAL_USAGE 
WITH 
  WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE 
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Standard warehouse for daily operations';

-- Set the context to use this warehouse immediately
USE WAREHOUSE GENERAL_USAGE;

--ROLE ACCESS

-- 1. Create the Role
CREATE ROLE IF NOT EXISTS FR_SERVAMERREPORTING_CONTRIBUTOR 

-- 2. Grant Warehouse Usage 
GRANT USAGE ON WAREHOUSE GENERAL_USAGE TO ROLE FR_SERVAMERREPORTING_CONTRIBUTOR;

-- 3. Grant Database Usage (
GRANT USAGE ON DATABASE CADP_SERV_AMER_REPORTING TO ROLE FR_SERVAMERREPORTING_CONTRIBUTOR;

-- 4. Grant Schema Privileges (
-- Usage allows them to see it; Create Table allows them to contribute
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA CADP_SERV_AMER_REPORTING.CURATED TO ROLE FR_SERVAMERREPORTING_CONTRIBUTOR;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA CADP_SERV_AMER_REPORTING.STAGING TO ROLE FR_SERVAMERREPORTING_CONTRIBUTOR;

-- 5. Grant current user the role (so you can test it)
GRANT ROLE FR_SERVAMERREPORTING_CONTRIBUTOR TO USER williamjohnson;

-- Setting your context first
USE ROLE FR_SERVAMERREPORTING_CONTRIBUTOR;
USE WAREHOUSE GENERAL_USAGE;
USE DATABASE CADP_SERV_AMER_REPORTING;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE PRODUCT_EXCEL (
    PRODUCT_NAME         VARCHAR(255),
    PRODUCT_CATEGORY     VARCHAR(100),
    PRODUCT_PRICE        NUMBER(10, 2),
    PRODUCT_DESCRIPTION  VARCHAR(16777216), -- Snowflake's max string length
    PRODUCT_BRAND        VARCHAR(100),
    PRODUCT_COLOR        VARCHAR(50),
    PRODUCT_SIZE         VARCHAR(10),
    PRODUCT_WEIGHT       NUMBER(10, 2),
    PRODUCT_QUANTITY     INT,
    PRODUCT_RELEASE_DATE DATE
);

SELECT COUNT(*) FROM PRODUCT_EXCEL --1000